#!/usr/bin/env python
import sys

for line in file(sys.argv[1]):
    code,afr,eng = line.strip().split("\t")
    print "\t".join([code, afr + ' (4 jr)', eng + ' (4 yr)'])
    print "\t".join([code.lower(), afr + ' (5 jr)', eng + ' (5 yr)'])

