<?xml version="1.0" ?>
<xsl:stylesheet version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="text" />

<xsl:template match="period">  \makewhite{} \periodlabel{<xsl:value-of select="concat(./@number, ' ', ./@starttime)" />}<xsl:apply-templates select="year" /> \hline
</xsl:template>

<xsl:template match="year">
    <xsl:if test="not(./@number='1')">\makewhite{}</xsl:if> <xsl:if test="./@number='1' or ./@number='3'">\shade{} </xsl:if> &amp; <xsl:value-of select="./@number" />\yearstrut{} &amp; <xsl:apply-templates select="day"/> \\
</xsl:template>

<xsl:template match="day">
  <xsl:choose> <xsl:when test="./module/@language='B'"> \widebox{<xsl:if test="../@number='1' or ../@number='3'">>{\shade{}}</xsl:if>c|}{<xsl:apply-templates select="module[./@language='B']"/>} </xsl:when> 
  <xsl:otherwise> 
    \narrowbox{<xsl:apply-templates select="module[./@language='A']" />} &amp; \narrowbox{<xsl:apply-templates select="module[./@language='E']" />} </xsl:otherwise> </xsl:choose> &amp; \lectbox{<xsl:for-each select="module"> <xsl:sort lang="C" select="./@language"/> <xsl:apply-templates select="." mode="lect"/> </xsl:for-each>} <xsl:if test="not(position()=last())">&amp;</xsl:if>
</xsl:template>

<xsl:template match="module"> \subject{<xsl:if test="./@type='P' or ./@type='T'">(</xsl:if> <xsl:value-of select="translate(./@name, ' ', ' ')" /> <xsl:if test="./@type='P' or ./@type='T'">)</xsl:if>} \\ \venue{<xsl:value-of select="./@venue"/>} <xsl:if test="not(position()=last())">\\</xsl:if> </xsl:template>

<xsl:template match="module" mode="lect">
  \lecturer{<xsl:value-of select="translate(./@responsible, '/', ' ')" />}
</xsl:template>

<xsl:template match="semester">
  <xsl:param name="startperiod" select="1" />
  <xsl:param name="endperiod" select="10" />
  \printtitle{<xsl:value-of select="/timetable/geninfo/@dept"/> - Semester <xsl:value-of select="./@number"/> of <xsl:value-of select="/timetable/@year"/> (generated on <xsl:value-of select="/timetable/geninfo/@date"/> )} \\ 

  \fontsize{7pt}{2pt}\usefont{T1}{phv}{m}{n}
  \begin{tabular}{|@{}ll|c|c|L|c|c|L|c|c|L|c|c|L|c|c|L|}
    \hline
    &amp; Yr &amp; \multicolumn{3}{>{\shade{}}c|}{Ma/Mo} &amp;
    \multicolumn{3}{>{\shade{}}c|}{Di/Tu} &amp;
    \multicolumn{3}{>{\shade{}}c|}{Wo/We} &amp;
    \multicolumn{3}{>{\shade{}}c|}{Do/Th} &amp;
    \multicolumn{3}{>{\shade{}}c|}{Vr/Fr} \\
    &amp; &amp; Afr &amp; Eng &amp; L &amp; Afr &amp; Eng &amp; L &amp; Afr &amp; Eng &amp; L &amp; Afr &amp; Eng &amp; L &amp; Afr &amp; Eng &amp; L\\
    \hline
    <xsl:apply-templates select="period[(./@number >= $startperiod) and ($endperiod >= ./@number) ]" />
    \end{tabular} \\
    \credits{Generated by <xsl:value-of select="/timetable/geninfo/@generator" /> version <xsl:value-of select="/timetable/geninfo/@version" />}
  \newpage

</xsl:template>

<xsl:template match="/timetable">
  \documentclass[a4paper]{article}
  \sloppy
  \usepackage[tmargin=8mm,lmargin=3mm,rmargin=3mm,bmargin=5mm]{geometry}
  \usepackage{multirow}
  \usepackage{color}
  \definecolor{countershade}{gray}{0.95}
  \usepackage{colortbl}
  \usepackage{array}
  \setlength{\arraycolsep}{0pt}
  \usepackage{graphicx}
  \newcolumntype{L}{m{0.04\textwidth}}
% Thick rules
%  \newcolumntype{I}{!{\vrule width 2pt}}
%  \newcommand\whline{\noalign{\global\savedwidt\arrayruelwidth\global\arrayrulewidth 2pt}\hline\noalign{\global\arrayrulewidth\savedwidth}}
  \newcommand\widebox[2]{\multicolumn{2}{#1}{\parbox{0.08\textwidth}{\centering #2}}}
  \newcommand\narrowbox[1]{\parbox{0.04\textwidth}{\centering #1}}
  \newcommand\lectbox[1]{{\centering #1\\}}
  \newcommand\subject[1]{{\fontsize{6pt}{2pt}\usefont{T1}{phv}{m}{n} #1}}
  \newcommand\venue[1]{{\fontsize{5pt}{2pt}\usefont{T1}{phv}{m}{n} #1}}
  \newcommand\lecturer[1]{{\fontsize{5pt}{2pt}\usefont{T1}{phv}{m}{n} #1}}
  \newcommand\printtitle[1]{\fontsize{10pt}{2pt}\usefont{T1}{phv}{m}{n} #1}
  \newcommand\credits[1]{\fontsize{5pt}{2pt}\usefont{T1}{phv}{m}{n} #1}
  \newcommand\yearstrut{\rule{0pt}{2ex}}
  \newcommand\shade{\rowcolor{countershade}}
  \newcommand\periodlabel[1]{\multirow{4}{*}{\rotatebox{90}{#1}}}
  \newcommand\makewhite{\multicolumn{1}{|c}{}}
  \pagestyle{empty}
  \thispagestyle{empty}
  \begin{document}
  \tiny
  \centering
  <xsl:for-each select="semesters/semester">
    <xsl:apply-templates select="." >
      <xsl:with-param name="startperiod" select="1" />
      <xsl:with-param name="endperiod" select="10" />
    </xsl:apply-templates>
  </xsl:for-each>
  \end{document}
</xsl:template>

</xsl:stylesheet>
