#!/bin/bash

# Process yearbook.pdf to find the counts of subjects and discipline-specific information

#pdftotext -layout -eol unix -nopgbrk yearbook.pdf yearbook.txt

yearbook=$1

engpattern="^([a-z]) [^ ]* Engineering$"
start4yr="Four-year Programmes"
start5yr="^Eng.*Engineering Augmented Degree Programme"
end5yr="REQUIREMENTS FOR PROMOTION"

echo "Extracting course info"
# List of disciplines:
grep "$engpattern" $yearbook | sort | uniq | cut -d " " -f 2- > disciplines

# counts for all subjects
python ./count_yearbook.py $yearbook > counts.txt

# extract 4 and 5 year plans
sed -n "/$start4yr/,\$p" $yearbook | sed -n "1,/$start5yr/p" > 4yr.txt
sed -n "/$start5yr/,/$end5yr/p" $yearbook > 5yr.txt

wc -l $1 disciplines counts.txt [45]yr.txt

echo 
echo "Extracting subjects per discipline"

# subjects per discipline
for plan in 4yr 5yr ; do
    cat disciplines | while read disc; do
	code=`echo $disc | tr " " "_" | grep -f - shortcodes | cut -f 1`
	if [ $plan == 5yr ] ; then
	    code=`echo $code | tr '[:upper:]' '[:lower:]'`
	fi
	echo -n $disc, $plan "plan "
	sed -n "/\([a-z]\).*$disc/,/$engpattern/p" $plan.txt \
 	    | egrep '^.?[A-Z]{3}' \
 	    | tr -d " *\t()" \
 	    | cut -c 1-6 \
	    | egrep '[A-Z]{3}[0-9]{3}' \
	    | sort \
	    | uniq \
	    > subjects_${code}$plan.txt
	wc -l subjects_${code}$plan.txt
    done
done


